# Generated by Django 4.1.7 on 2023-02-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_alter_profile_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='ID пользователя в соц сети'),
        ),
    ]
