# Generated by Django 4.1.7 on 2023-02-17 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0005_alter_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(validators=[django.core.validators.RegexValidator(code='^\\d+ [А-я]+$', message='сумма + категория')], verbose_name='Текст'),
        ),
    ]
