# Generated by Django 4.1.7 on 2023-02-20 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0007_alter_message_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='MonthsEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.PositiveIntegerField(verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.categoryex', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='DayEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.PositiveIntegerField(verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.categoryex', verbose_name='Категория')),
            ],
        ),
    ]
