# Generated by Django 4.1.7 on 2023-02-20 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0008_categoryex_monthsex_dayex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryex',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='dayex',
            options={'verbose_name': 'День', 'verbose_name_plural': 'День'},
        ),
        migrations.AlterModelOptions(
            name='monthsex',
            options={'verbose_name': 'Месяц', 'verbose_name_plural': 'Месяц'},
        ),
        migrations.AddField(
            model_name='dayex',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ugc.profile', verbose_name='Профиль'),
        ),
        migrations.AddField(
            model_name='monthsex',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ugc.profile', verbose_name='Профиль'),
        ),
    ]
