# Generated by Django 4.1.7 on 2023-02-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0009_alter_categoryex_options_alter_dayex_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayex',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Время получения'),
        ),
    ]
